config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_categories
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :new, :create, :show]
  resources :rentals, only: [:index, :new, :create, :show] do
    resources :car_rentals, only: [:new, :create]
    get 'search', on: :collection
  end
  namespace :api do
    namespace :v1 do
      resources :cars, only: [:index, :show, :create]
    end
  end
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
  validates :name, :address, :cnpj, presence: true
  validates :cnpj, uniqueness: true
  validate :cnpj_must_be_valid

  def cnpj_must_be_valid
    return if cnpj.blank? || CNPJ.valid?(cnpj)
    errors.add(:cnpj, 'não é válido')
  end
end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController
  before_action :authenticate_user!

  def index
    @subsidiaries = Subsidiary.all
  end

  def show
    @subsidiary = Subsidiary.find(params[:id])
  end

  def new
    @subsidiary = Subsidiary.new
  end

  def create
    @subsidiary = Subsidiary.create(subsidiary_params)
    redirect_to @subsidiary
  end

  def edit
    @subsidiary = Subsidiary.find(params[:id])
  end

  def update
    @subsidiary = Subsidiary.find(params[:id])
    if @subsidiary.update(subsidiary_params)
      redirect_to @subsidiary
    else
      render :edit
    end
  end

  private

  def subsidiary_params
    params.require(:subsidiary).permit(:name, :cnpj, :address)
  end
end

app/views/subsidiaries/_form.html.erb
<% if subsidiary.errors.any? %>
  <ul>
    <% subsidiary.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: subsidiary, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cnpj %>
  <%= f.text_field :cnpj %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit 'Enviar'%>
<% end %>

app/views/subsidiaries/edit.html.erb
<h1>Atualizar filial <%= @subsidiary.name %></h1>

<%= render partial: 'form', locals: {subsidiary: @subsidiary} %>

app/views/subsidiaries/index.html.erb
<% @subsidiaries.each do |subsidiary| %>
  <%= link_to subsidiary.name, subsidiary_path(subsidiary.id) %>
<% end %>

<% if @subsidiaries.empty? %>
  <h3>Nenhuma filial cadastrada</h3>
<% end %>

<%= link_to 'Registrar uma nova filial', new_subsidiary_path %>
<%= link_to  'Voltar', root_path %>

app/views/subsidiaries/new.html.erb
<%= form_with model: @subsidiary, local: true do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :cnpj, 'CNPJ' %>
  <%= f.text_field :cnpj %>
  <%= f.label :address, 'Endereço'%>
  <%= f.text_field :address %>
  <%= f.submit 'Enviar'%>
<% end %>

app/views/subsidiaries/show.html.erb
<h1><%= @subsidiary.name %></h1>

<dl>
  <dt>CNPJ</dt>
  <dd><%= @subsidiary.cnpj %></dd>
  <dt>Endereço</dt>
  <dd><%= @subsidiary.address %></dd>
</dl>

<%= link_to  "Editar", edit_subsidiary_path(@subsidiary.id)  %>
<%= link_to  "Voltar", subsidiaries_path %>