config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_categories
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :new, :create, :show]
  resources :rentals, only: [:index, :new, :create, :show] do
    resources :car_rentals, only: [:new, :create]
    get 'search', on: :collection
  end
  namespace :api do
    namespace :v1 do
      resources :cars, only: [:index, :show, :create]
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :document, :email, presence: true
  validates :document, :email, uniqueness: true
  validates :document, 
            format: { with: /\A\d{3}\.\d{3}\.\d{3}\-\d{2}\z/, message: "deve ter o formato XXX.XXX.XXX-XX" },
            length: { is: 14 }
  validate :document_must_be_valid

  def information
    "#{name} - #{document}"
  end

  private

  def document_must_be_valid
    return if document.blank? || CPF.valid?(document)
    errors.add(:document, 'não é válido')
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer, notice: 'Cliente cadastrado com sucesso!'
    else
      render :new
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :document, :email)
  end
end

app/views/customers/_form.html.erb
<% customer.errors.full_messages.each do |message| %>
<p><%= message %></p>
<% end %>

<%= form_with model: customer, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :document %>
  <%= f.text_field :document %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/customers/index.html.erb
<h1>Clientes</h1>

<%= link_to  "Cadastrar cliente", new_customer_path %>

app/views/customers/new.html.erb
<h1>Novo cliente</h1>

<%= render partial: 'form', locals: { customer: @customer } %>

app/views/customers/show.html.erb
<h1><%= @customer.name %></h1>

<dl>
  <dt><%= Customer.human_attribute_name :name %></dt>
  <dd><%= @customer.name %></dd>
  <dt><%= Customer.human_attribute_name :document %></dt>
  <dd><%= @customer.document %></dd>
  <dt><%= Customer.human_attribute_name :email %></dt>
  <dd><%= @customer.email %></dd>
</dl>