config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_categories
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :new, :create, :show]
  resources :rentals, only: [:index, :new, :create, :show] do
    resources :car_rentals, only: [:new, :create]
    get 'search', on: :collection
  end
  namespace :api do
    namespace :v1 do
      resources :cars, only: [:index, :show, :create]
    end
  end
end

app/models/car_category.rb
class CarCategory < ApplicationRecord
  has_many :car_models
  has_many :cars, through: :car_models

  validates :name, :daily_rate, :car_insurance,
            :third_party_insurance, presence: true

  validates :name, uniqueness: { case_sensitive: false }

  def daily_price 
    daily_rate + car_insurance + third_party_insurance
  end

end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @car_categories = CarCategory.all
  end

  def show
    @car_category = CarCategory.find(params[:id])
  end

  def new
    @car_category = CarCategory.new
  end

  def create
    @car_category = CarCategory.new(car_category_params)
    if @car_category.save
      redirect_to @car_category
    else
      render :new
    end
  end

  def edit
    @car_category = CarCategory.find(params[:id])
  end

  def update
    @car_category = CarCategory.find(params[:id])
    if @car_category.update(car_category_params)
      redirect_to @car_category
    else
      render :edit
    end
  end

  def destroy
    @car_category = CarCategory.find(params[:id])
    @car_category.destroy
    redirect_to car_categories_path
  end

  private

  def car_category_params
    params.require(:car_category)
          .permit(:name, :daily_rate, :car_insurance, :third_party_insurance)
  end
end

app/views/car_categories/_form.html.erb
<% if car_category.errors.any? %>
  <ul>
    <% car_category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: car_category, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :daily_rate %>
  <%= f.number_field :daily_rate, min: 0 %>
  <%= f.label :car_insurance %>
  <%= f.number_field :car_insurance, min: 0 %>
  <%= f.label :third_party_insurance %>
  <%= f.number_field :third_party_insurance, min: 0 %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/car_categories/edit.html.erb
<h1>Atualizar categoria <%= @car_category.name %></h1>
<%= render partial: 'form', locals: {car_category: @car_category} %>

app/views/car_categories/index.html.erb
<% @car_categories.each do |category| %>
  <%= link_to category.name, category %>
<% end %>

<% if @car_categories.empty? %>
  <h3>Nenhuma categoria cadastrada</h3>
<% end %>

<%= link_to "Registrar uma nova categoria", new_car_category_path %>

<%= link_to  "Voltar", root_path %>

app/views/car_categories/new.html.erb
<h1>Nova categoria</h1>

<%= render partial: 'form', locals: {car_category: @car_category} %>

app/views/car_categories/show.html.erb
<h1>
  <%= @car_category.name %>
</h1>

<dl>
  <dt><%= CarCategory.human_attribute_name(:daily_rate) %></dt>
  <dd><%= number_to_currency @car_category.daily_rate %></dd>
  <dt><%= CarCategory.human_attribute_name(:car_insurance) %></dt>
  <dd><%= number_to_currency @car_category.car_insurance %></dd>
  <dt><%= CarCategory.human_attribute_name(:third_party_insurance) %></dt>
  <dd><%= number_to_currency @car_category.third_party_insurance %></dd>
</dl>

<h2>Modelos disponíveis</h2>
<% if @car_category.car_models.empty? %>
  <h3>Nenhum modelo de carro cadastrado nessa categoria</h3>
<% else %>
  <table>
    <tr>
      <th><%= CarModel.human_attribute_name :name %></th>
      <th><%= CarModel.human_attribute_name :year %></th>
      <th><%= CarModel.human_attribute_name :manufacturer %></th>
      <th><%= CarModel.human_attribute_name :motorization %></th>
      <th><%= CarModel.human_attribute_name :fuel_type %></th>
    </tr>
    <% @car_category.car_models.each do |model| %>
      <tr>
        <td><%= link_to model.name, model %></td>
        <td><%= model.year %></td>
        <td><%= model.manufacturer %></td>
        <td><%= model.motorization %></td>
        <td><%= model.fuel_type %></td>
      </tr>
    <% end %>
  </table>
<% end %>
<br />
<%= link_to  "Editar", edit_car_category_path(@car_category) %>
<%= link_to  "Apagar", car_category_path(@car_category), method: :DELETE, data: {confirm: 'Apagar esta categoria?'} %>
<%= link_to  "Voltar", car_categories_path %>