config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_categories
  resources :subsidiaries, only: [:index, :show, :new, :create, :edit, :update]
  resources :car_models, only: [:index, :show, :new, :create]
  resources :customers, only: [:index, :new, :create, :show]
  resources :rentals, only: [:index, :new, :create, :show] do
    resources :car_rentals, only: [:new, :create]
    get 'search', on: :collection
  end
  namespace :api do
    namespace :v1 do
      resources :cars, only: [:index, :show, :create]
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :customer
  belongs_to :car_category
  belongs_to :user
  has_one :car_rental

  validates :start_date, :end_date, presence: true

  before_create :generate_code

  def estimated_value
    number_of_days_rented = end_date - start_date
    number_of_days_rented * car_category.daily_price
  end

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create]
  def index
    @rentals = Rental.all
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
    @customers = Customer.all
    @car_categories = CarCategory.all
  end

  def create
    @rental = Rental.new(rental_params)
    @customers = Customer.all
    @car_categories = CarCategory.all
    @rental.user = current_user

    if @rental.save
      redirect_to @rental, notice: 'Agendamento realizado com sucesso'
    else
      render :new
    end
  end

  def search
    @is_search = true
    @rentals = Rental.where('code LIKE UPPER(?)', "%#{params[:q]}%")
    render :index
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :customer_id, :car_category_id)
  end
end

app/views/rentals/_form.html.erb
<% rental.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: rental, local: true do |f| %>
<%= f.label :start_date %>
<%= f.date_field :start_date %>
<%= f.label :end_date %>
<%= f.date_field :end_date %>
<%= f.label :customer_id %>
<%= f.collection_select :customer_id, customers, :id, :information %>
<%= f.label :car_category_id %>
<%= f.collection_select :car_category_id, car_categories, :id, :name %>
<%= f.submit 'Agendar' %>
<% end %>

app/views/rentals/_rental.html.erb
<dl>
  <dt><%= Rental.human_attribute_name :code %></dt>
  <dd><%= rental.code %></dd>
  <dt><%= Rental.human_attribute_name :start_date %></dt>
  <dd><%= l rental.start_date %></dd>
  <dt><%= Rental.human_attribute_name :end_date %></dt>
  <dd><%= l rental.end_date %></dd>
  <dt><%= Rental.human_attribute_name :customer %></dt>
  <dd><%= rental.customer.information %></dd>
  <dt><%= Rental.human_attribute_name :customer %></dt>
  <dd>
    <%= rental.customer.name %>
    <%= rental.customer.document %>
    <%= rental.customer.email %>
  </dd>
  <dt><%= Rental.human_attribute_name :car_category %></dt>
  <dd><%= rental.car_category.name %></dd>
  <dt><%= Rental.human_attribute_name :user %></dt>
  <dd><%= rental.user.name %></dd>
  <dt><%= Rental.human_attribute_name :estimated_value %></dt>
  <dd><%= number_to_currency rental.estimated_value %></dd>
</dl>

app/views/rentals/index.html.erb
<h1>Locações</h1>

<% if @rentals.empty? %>
  <p><%= @is_search ? 'Nenhuma locação encontrada' : 'Nenhuma locação cadastrada'%></p>
<% else %>
  <%= form_with url: search_rentals_path, method: :get, local: true do |f| %>
    <%= f.label :q, 'Busca de locação' %>
    <%= f.text_field :q %>
    <%= f.submit 'Buscar' %>
  <% end %>
  <table>
    <tr>
      <th><%= Rental.human_attribute_name :code%></th>
      <th><%= Rental.human_attribute_name :start_date%></th>
      <th><%= Rental.human_attribute_name :end_date%></th>
      <th><%= Rental.human_attribute_name :customer%></th>
      <th><%= Rental.human_attribute_name :car_category%></th>
      <th><%= Rental.human_attribute_name :estimated_value%></th>
    </tr>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= link_to rental.code, rental %></td>
        <td><%= rental.start_date%></td>
        <td><%= rental.end_date%></td>
        <td><%= rental.customer.information%></td>
        <td><%= rental.car_category.name%></td>
        <td><%= number_to_currency rental.estimated_value%></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to  "Voltar", @is_search ? rentals_path : root_path %>

<%= link_to 'Agendar nova locação', new_rental_path %>

app/views/rentals/new.html.erb
<h1>Nova locação</h1>

<%= render partial: 'form', locals: {rental: @rental, customers: @customers, car_categories: @car_categories} %>

app/views/rentals/show.html.erb
<h1>Locação <%= @rental.id %></h1>

<%= render @rental %>

<% if @rental.car_rental %>
  <h2>Locação em andamento</h2>
  <span>Carro escolhido: </span><%= @rental.car_rental.car.information %><br/>
  <span>CNH do condutor: </span><%= @rental.car_rental.driver_license_number %><br/>
  <span>Iniciada por: </span><%= "#{@rental.car_rental.user.name} (#{@rental.car_rental.user.email})" %><br/>
  <span>Em: </span><%= l @rental.car_rental.start_date, format: :short %>

<% else %>
  <%= link_to  "Iniciar locação", new_rental_car_rental_path(@rental) %>
<% end %>

<%= link_to  "Voltar", rentals_path %>